feat: Update credentials for multi arch images
tektoncd/plumbing pull request #2326
Opened 2024-12-02 16:55 UTC by LiteBrick204

# Changes

This is for #2223
/kind feature
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

2024-12-02 17:09 UTC, LiteBrick204 commented
/test check-pr-has-kind-label

2024-12-02 18:19 UTC, AlanGreene commented on tekton/resources/images/docker-multi-arch-template.yaml
> +            docker login -u ${IMAGE_REGISTRY_USER} --password-stdin ${IMAGE_REGISTRY_TOKEN}
Same feedback as on https://github.com/tektoncd/plumbing/pull/2327 re. correct use of `--password-stdin`

2024-12-03 11:26 UTC, AlanGreene requested changes

2024-12-03 11:26 UTC, AlanGreene commented on tekton/resources/images/docker-multi-arch-template.yaml
> +            docker login ghcr.io -u ${IMAGE_REGISTRY_USER} --password-stdin < ${"$IMAGE_REGISTRY_CREDENTIALS"}
This causes an error due to unterminated string. The following works:

```suggestion
            docker login ghcr.io -u ${IMAGE_REGISTRY_USER} --password-stdin < "${IMAGE_REGISTRY_CREDENTIALS}"
```

2024-12-03 17:15 UTC, AlanGreene approved these changes

2024-12-03 17:40 UTC, vdemeester approved these changes

2024-12-03 18:09 UTC, afrittoli reviewed
/lgtm

2024-12-03 18:10 UTC, merged